[package]
name = "crossplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.4.0"
dioxus = { version = "0.2.4", features = ["desktop"] }
tokio = { version = "1.19.2", features = ["macros"] }
