[package]
name = "crossplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.4.0"
console-subscriber = "0.1.6"
dioxus = { version = "0.2.4", features = ["desktop"] }
id3 = "1.1.3"
regex = "1.5.6"
serde = "1.0.137"
serde_json = "1.0.81"
tokio = { version = "1.19.2", features = ["macros"] }
