#!/bin/bash
export PKG_CONFIG_PATH="/opt/homebrew/Cellar/gstreamer/1.20.3/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export GST_PLUGIN_SYSTEM_PATH=/opt/homebrew/Cellar/gst-plugins-base/1.20.3/lib:/opt/homebrew/lib/gstreamer-1.0/
